name: Terraform-Kind-CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          cd examples/basic-cluster
          terraform init
          terraform validate

      - name: Run Terratest
        run: |
          cd test
          go mod tidy
          go test -v
